source 'https://rubygems.org'

gem 'fastlane', '2.230.0'
gem 'cocoapods', '1.16.1'
gem 'nokogiri', '1.15.3'
gem 'json', '2.7.1'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)