---
version: 2

plan:
  name: TrustTunnel — translations sync
  key: TRANSLATIONSSYNC
  project-key: TT

stages:
  - Default stage:
      manual: true # Change to false whenever localization files will be
      final: false
      jobs:
        - Synchronizing translations

notifications: []

labels: []

triggers: [] # Uncomment cron below when localization will be provided
  #- cron: 0 0 3 ? * MON,TUE,WED,THU,FRI *

branches:
  create: manually
  delete: never
  link-to-jira: false

other:
  concurrent-build-plugin: '1'

Synchronizing translations:
  key: SYNCHRONIZINGTRANSLATIONS
  docker:
    image: adguard/android-base:2.9 # We reuse this image because it's suitable for the plan
  tasks:
    - !include task-clean-all.yaml
    - checkout:
        repository: vpn-oss-gui
        path: trusttunnel
        force-clean-build: 'true'
    - checkout:
        repository: slack-scripts
        path: slack-scripts
        force-clean-build: true
    - checkout:
        repository: mobile-twosky-kit
        path: mobile-twosky-kit
        force-clean-build: true
    - checkout:
        repository: mobile-ci-scripts
        path: mobile-ci-scripts
        force-clean-build: true
    - checkout:
        repository: git-scripts
        path: git-scripts
        force-clean-build: 'true'
    - script: mobile-ci-scripts/sync_translations.sh "${bamboo_working_directory}/git-scripts/git_kit.sh" "${bamboo_working_directory}/slack-scripts/slack_kit.py" "${bamboo_working_directory}/mobile-twosky-kit/twosky_kit.py" "${bamboo_working_directory}/trusttunnel/" "${bamboo_working_directory}/trusttunnel/" vpn-oss-gui-2-1 https://crowdin.com/editor/adguard-applications/19687/en-en adguard-translations "$bamboo_planRepository_1_repositoryUrl"
