---
version: 2
plan:
  name: TrustTunnel — build number increment
  key: BUILDINCREMENT
  project-key: TT

stages:
  - Increment:
      manual: false
      final: false
      jobs:
        - Increment build number

notifications: []

labels: []

branches:
  create: for-new-branch
  delete:
    after-deleted-days: 1

other:
  concurrent-build-plugin: '1'

Increment build number:
  key: INCREMENTBUILDNUMBER
  docker:
    image: adguard/android-base:2.9 # We reuse this image because it's suitable for the plan
  tasks:
    - !include task-clean-all.yaml
    - checkout:
        path: trusttunnel
        force-clean-build: true
    - checkout:
        repository: git-scripts
        path: git-scripts
        force-clean-build: true
    - script: trusttunnel/bamboo-specs/scripts/increment_build_number_and_push.sh "${bamboo_working_directory}/git-scripts/git_kit.sh"
  requirements: [ adg-privileged-docker ]
